# -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8 -*-
# ------------------------------------------------------------------------------
# Copyright 2022-2026 Alexandre l'Heritier
# See the top-level LICENSE file for details.
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
# external.zsh
#
# Check availability of external progs.
# ------------------------------------------------------------------------------



if [[ ! -v PZC_PZC_CACHE_DIR ]]
then
  PZC_PZC_CACHE_DIR=${HOME}/.cache/pzc
fi

PZC_PZC_PKG_LOCATION_FILE=${PZC_PZC_CACHE_DIR}/pkg_location



function _pzc_generate_config()
{
  PZC_PZC_CONFIG_PKGS=${PZC_PZC_CONFIG_DIR}/pkgs.json
  if [[ ! -e ${PZC_PZC_CONFIG_PKGS} ]]
  then
    _pzc_error "pkgs.json not found"
    return 1
  fi

  # ---------------------------------------

  rm -f ${PZC_PZC_PKG_LOCATION_FILE}
  _pzc_info "Generating config file..."
  echo "# Generated by PZC. Do not edit." >> ${PZC_PZC_PKG_LOCATION_FILE}

  # ---------------------------------------

  local PZC_ENABLE_OMP=$(jq -r '.pzc_config_pkgs.pkgs.oh_my_posh.enable' ${PZC_PZC_CONFIG_PKGS})
  if [[ ${PZC_ENABLE_OMP} = true ]]
  then
    local PZC_OMP_BIN=$(jq -r '.pzc_config_pkgs.pkgs.oh_my_posh.executable_path' ${PZC_PZC_CONFIG_PKGS})
    if [[ "${PZC_OMP_BIN}" != "" ]]
    then
      if [[ -e ${PZC_OMP_BIN} ]]
      then
        _pzc_debug "PZC_OMP_BIN = ${PZC_OMP_BIN} (user defined)"
      else
        _pzc_warning "Your Oh-My-Posh is not found. Search other Oh-My-Posh."
        PZC_OMP_BIN=""
      fi
    fi
    if [[ "${PZC_OMP_BIN}" == "" ]]
    then
      if [[ ${_PZC_MISE_AVAILABLE} = 1 ]]
      then
        PZC_OMP_BIN=$(${PZC_MISE_BIN} which --raw -E ${HOST} -C "${ENVI_DIR}/pzc/progs/mise" oh-my-posh 2&>/dev/null)
        if [[ $? == 0 ]]
        then
          _pzc_debug "PZC_OMP_BIN = ${PZC_OMP_BIN} (Mise-en-place)"          
        fi
      fi
    fi
    if [[ "${PZC_OMP_BIN}" == "" ]]
    then
      if [[ -x "$(command -v oh-my-posh)" ]]
      then
        PZC_OMP_BIN=oh-my-posh
        _pzc_debug "PZC_OMP_BIN = ${PZC_OMP_BIN} (Path)"
      fi
    fi
    if [[ "${PZC_OMP_BIN}" == "" ]]
    then
      _pzc_warning "Oh-My-Posh is not installed (https://github.com/JanDeDobbeleer/oh-my-posh). You can install Oh-My-Posh with Mise-en-place with the command 'pzc_install_omp' or disable Oh-My-Posh search in pzcrc."
    fi
  fi

  echo "_PZC_OMP_BIN=\"${PZC_OMP_BIN}\"" >> ${PZC_PZC_PKG_LOCATION_FILE}

  # ---------------------------------------
  # ---------------------------------------

}
