# -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8 -*-
# ------------------------------------------------------------------------------
# Copyright 2022-2026 Alexandre l'Heritier
# See the top-level LICENSE file for details.
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
# external.zsh
#
# Check availability of external progs.
# ------------------------------------------------------------------------------



if [[ ! -v PZC_PZC_CACHE_DIR ]]
then
  PZC_PZC_CACHE_DIR=${HOME}/.cache/pzc
fi

PZC_PZC_PKG_LOCATION_FILE=${PZC_PZC_CACHE_DIR}/pkg_location



function _pzc_generate_config()
{
  PZC_PZC_CONFIG_PKGS=${PZC_PZC_CONFIG_DIR}/pkgs.json
  if [[ ! -e ${PZC_PZC_CONFIG_PKGS} ]]
  then
    _pzc_error "pkgs.json not found"
    return 1
  fi

  # ---------------------------------------

  rm -f ${PZC_PZC_PKG_LOCATION_FILE}
  _pzc_info "Generating config file..."
  echo "# Generated by PZC. Do not edit." >> ${PZC_PZC_PKG_LOCATION_FILE}

  # ---------------------------------------
  # OhMyPosh
  # ---------------------------------------

  local PZC_ENABLE_OMP=$(jq -r '.pzc_config_pkgs.pkgs.oh_my_posh.enable' ${PZC_PZC_CONFIG_PKGS})
  if [[ ${PZC_ENABLE_OMP} = true ]]
  then
    local PZC_OMP_BIN=$(jq -r '.pzc_config_pkgs.pkgs.oh_my_posh.executable_path' ${PZC_PZC_CONFIG_PKGS})
    if [[ "${PZC_OMP_BIN}" != "" ]]
    then
      if [[ -e ${PZC_OMP_BIN} ]]
      then
        _pzc_debug "PZC_OMP_BIN = ${PZC_OMP_BIN} (user defined)"
      else
        _pzc_warning "Your Oh-My-Posh is not found. Search other Oh-My-Posh."
        PZC_OMP_BIN=""
      fi
    fi
    if [[ "${PZC_OMP_BIN}" == "" ]]
    then
      if [[ ${_PZC_MISE_AVAILABLE} = 1 ]]
      then
        PZC_OMP_BIN=$(${PZC_MISE_BIN} which --raw -E ${HOST} -C "${ENVI_DIR}/pzc/progs/mise" oh-my-posh 2&>/dev/null)
        if [[ $? == 0 ]]
        then
          _pzc_debug "PZC_OMP_BIN = ${PZC_OMP_BIN} (Mise-en-place)"
        fi
      fi
    fi
    if [[ "${PZC_OMP_BIN}" == "" ]]
    then
      if [[ -x "$(command -v oh-my-posh)" ]]
      then
        PZC_OMP_BIN=oh-my-posh
        _pzc_debug "PZC_OMP_BIN = ${PZC_OMP_BIN} (Path)"
      fi
    fi
    if [[ "${PZC_OMP_BIN}" == "" ]]
    then
      _pzc_warning "Oh-My-Posh is not installed (https://github.com/JanDeDobbeleer/oh-my-posh). You can install Oh-My-Posh with Mise-en-place with the command 'pzc_install_omp' or disable Oh-My-Posh search in pzcrc."
    fi

    local PZC_OMP_THEME_FILE=$(jq -r '.pzc_config_pkgs.pkgs.oh_my_posh.theme_file' ${PZC_PZC_CONFIG_PKGS})
    if [[ "${PZC_OMP_THEME_FILE}" != "" ]]
    then
      if [[ -e ${PZC_OMP_THEME_FILE} ]]
      then
        _pzc_debug "PZC_OMP_THEME_FILE = ${PZC_OMP_THEME_FILE} (user defined)"
      else
        _pzc_warning "Your Oh-My-Posh theme is not found. Set default Oh-My-Posh theme."
        PZC_OMP_THEME_FILE=""
      fi
    fi
    if [[ "${PZC_OMP_THEME_FILE}" == "" ]]
    then
      PZC_OMP_THEME_FILE=${PZC_PZC_DIR}/progs/oh-my-posh/themes/PZC.json
      _pzc_debug "PZC_OMP_THEME_FILE = ${PZC_OMP_THEME_FILE} (default)"
    fi
  fi

  echo "_PZC_OMP_BIN=\"${PZC_OMP_BIN}\"" >> ${PZC_PZC_PKG_LOCATION_FILE}
  echo "_PZC_OMP_THEME_FILE=\"${PZC_OMP_THEME_FILE}\"" >> ${PZC_PZC_PKG_LOCATION_FILE}



  # ---------------------------------------
  # EZA-LS
  # ---------------------------------------

  local PZC_ENABLE_EZA=$(jq -r '.pzc_config_pkgs.pkgs.eza.enable' ${PZC_PZC_CONFIG_PKGS})
  local PZC_ALIAS_EZA=0
  if [[ ${PZC_ENABLE_EZA} = true ]]
  then
    local PZC_EZA_BIN=$(jq -r '.pzc_config_pkgs.pkgs.eza.executable_path' ${PZC_PZC_CONFIG_PKGS})
    if [[ "${PZC_EZA_BIN}" != "" ]]
    then
      if [[ -e ${PZC_EZA_BIN} ]]
      then
        _pzc_debug "PZC_EZA_BIN = ${PZC_EZA_BIN} (user defined)"
        PZC_ALIAS_EZA=1
      else
        _pzc_warning "Your EZA is not found. Search other EZA."
        PZC_EZA_BIN=""
      fi
    fi
    if [[ "${PZC_EZA_BIN}" == "" ]]
    then
      if [[ ${_PZC_MISE_AVAILABLE} = 1 ]]
      then
        PZC_EZA_BIN=$(${PZC_MISE_BIN} which --raw -E ${HOST} -C "${ENVI_DIR}/pzc/progs/mise" eza 2&>/dev/null)
        if [[ $? == 0 ]]
        then
          _pzc_debug "PZC_EZA_BIN = ${PZC_EZA_BIN} (Mise-en-place)"
          PZC_ALIAS_EZA=1
        fi
      fi
    fi
    if [[ "${PZC_EZA_BIN}" == "" ]]
    then
      if [[ -x "$(command -v eza)" ]]
      then
        PZC_EZA_BIN=eza
        _pzc_debug "PZC_EZA_BIN = ${PZC_EZA_BIN} (Path)"
      fi
    fi
    if [[ "${PZC_EZA_BIN}" == "" ]]
    then
      _pzc_warning "Eza is not installed (https://github.com/eza-community/eza). You can install eza with Mise-en-place with the command 'pzc_install_eza' or disable eza search in pzcrc."
    fi

    local PZC_EZA_CONFIG_DIR=$(jq -r '.pzc_config_pkgs.pkgs.eza.config_dir' ${PZC_PZC_CONFIG_PKGS})
    if [[ "${PZC_EZA_CONFIG_DIR}" != "" ]]
    then
      if [[ -d ${PZC_EZA_CONFIG_DIR} ]]
      then
        _pzc_debug "PZC_EZA_CONFIG_DIR = ${PZC_EZA_CONFIG_DIR} (user defined)"
      else
        _pzc_warning "Your EZA config dir is not found. Search default EZA config dir."
        PZC_EZA_CONFIG_DIR=""
      fi
    fi
    if [[ "${PZC_EZA_CONFIG_DIR}" == "" ]]
    then
      PZC_EZA_CONFIG_DIR=${PZC_PZC_DIR}/progs/eza/config
      _pzc_debug "PZC_EZA_CONFIG_DIR = ${PZC_EZA_CONFIG_DIR} (default)"
    fi
  fi

  echo "PZC_EZA_BIN=\"${PZC_EZA_BIN}\"" >> ${PZC_PZC_PKG_LOCATION_FILE}
  echo "export EZA_CONFIG_DIR=\"${PZC_EZA_CONFIG_DIR}\"" >> ${PZC_PZC_PKG_LOCATION_FILE}
        
  if [[ ${PZC_ALIAS_EZA} = 1 ]]
  then
    echo "alias eza='${PZC_EZA_BIN}'" >> ${PZC_PZC_PKG_LOCATION_FILE}
  fi



  # ---------------------------------------
  # CCache
  # ---------------------------------------

  local PZC_ENABLE_CCACHE=$(jq -r '.pzc_config_pkgs.pkgs.ccache.enable' ${PZC_PZC_CONFIG_PKGS})
  local PZC_ALIAS_CCACHE=0
  if [[ ${PZC_ENABLE_CCACHE} = true ]]
  then
    local PZC_CCACHE_BIN=$(jq -r '.pzc_config_pkgs.pkgs.ccache.executable_path' ${PZC_PZC_CONFIG_PKGS})
    if [[ "${PZC_CCACHE_BIN}" != "" ]]
    then
      if [[ -e ${PZC_CCACHE_BIN} ]]
      then
        _pzc_debug "PZC_CCACHE_BIN = ${PZC_CCACHE_BIN} (user defined)"
        PZC_ALIAS_CCACHE=1
      else
        _pzc_warning "Your CCache is not found. Search other CCache."
        PZC_CCACHE_BIN=""
      fi
    fi
    if [[ "${PZC_CCACHE_BIN}" == "" ]]
    then
      if [[ ${_PZC_MISE_AVAILABLE} = 1 ]]
      then
        PZC_CCACHE_BIN=$(${PZC_MISE_BIN} which --raw -E ${HOST} -C "${ENVI_DIR}/pzc/progs/mise" ccache 2&>/dev/null)
        if [[ $? == 0 ]]
        then
          _pzc_debug "PZC_CCACHE_BIN = ${PZC_CCACHE_BIN} (Mise-en-place)"
          PZC_ALIAS_CCACHE=1
        fi
      fi
    fi
    if [[ "${PZC_CCACHE_BIN}" == "" ]]
    then
      if [[ -x "$(command -v ccache)" ]]
      then
        PZC_CCACHE_BIN=ccache
        _pzc_debug "PZC_CCACHE_BIN = ${PZC_CCACHE_BIN} (Path)"
      fi
    fi
    if [[ "${PZC_CCACHE_BIN}" == "" ]]
    then
      _pzc_warning "CCache is not installed (https://github.com/ccache/ccache). You can install ccache with Mise-en-place with the command 'pzc_install_ccache' or disable ccache search in pzcrc."
    fi
  fi

  echo "PZC_CCACHE_BIN=\"${PZC_CCACHE_BIN}\"" >> ${PZC_PZC_PKG_LOCATION_FILE}
  if [[ ${PZC_ALIAS_EZA} = 1 ]]
  then
    echo "alias ccache='${PZC_CCACHE_BIN}'" >> ${PZC_PZC_PKG_LOCATION_FILE}
  fi



  # ---------------------------------------
  # Mold
  # ---------------------------------------

  local PZC_ENABLE_MOLD=$(jq -r '.pzc_config_pkgs.pkgs.mold.enable' ${PZC_PZC_CONFIG_PKGS})

  if [[ ${PZC_ENABLE_MOLD} = true ]]
  then
    local PZC_MOLD_BIN=$(jq -r '.pzc_config_pkgs.pkgs.mold.executable_path' ${PZC_PZC_CONFIG_PKGS})
    if [[ "${PZC_MOLD_BIN}" != "" ]]
    then
      if [[ -e ${PZC_MOLD_BIN} ]]
      then
        _pzc_debug "PZC_MOLD_BIN = ${PZC_MOLD_BIN} (user defined)"
      else
        _pzc_warning "Your Mold is not found. Search other Mold."
        PZC_MOLD_BIN=""
      fi
    fi
    if [[ "${PZC_MOLD_BIN}" == "" ]]
    then
      if [[ ${_PZC_MISE_AVAILABLE} = 1 ]]
      then
        PZC_MOLD_BIN=$(${PZC_MISE_BIN} which --raw -E ${HOST} -C "${ENVI_DIR}/pzc/progs/mise" mold 2&>/dev/null)
        if [[ $? == 0 ]]
        then
          _pzc_debug "PZC_MOLD_BIN = ${PZC_MOLD_BIN} (Mise-en-place)"
        fi
      fi
    fi
    if [[ "${PZC_MOLD_BIN}" == "" ]]
    then
      if [[ -x "$(command -v mold)" ]]
      then
        PZC_MOLD_BIN="mold"
        _pzc_debug "PZC_MOLD_BIN = ${PZC_MOLD_BIN} (Path)"
      fi
    fi
    if [[ "${PZC_MOLD_BIN}" == "" ]]
    then
      _pzc_warning "Mold is not installed (https://github.com/rui314/mold). You can install mold with Mise-en-place with the command 'pzc_install_mold' or disable mold search in pzcrc."
    fi
  fi

  echo "PZC_MOLD_BIN=\"${PZC_MOLD_BIN}\"" >> ${PZC_PZC_PKG_LOCATION_FILE}



  # ---------------------------------------
  # Ninja
  # ---------------------------------------

  local PZC_ENABLE_NINJA=$(jq -r '.pzc_config_pkgs.pkgs.ninja.enable' ${PZC_PZC_CONFIG_PKGS})

  if [[ ${PZC_ENABLE_NINJA} = true ]]
  then
    local PZC_NINJA_BIN=$(jq -r '.pzc_config_pkgs.pkgs.ninja.executable_path' ${PZC_PZC_CONFIG_PKGS})
    if [[ "${PZC_NINJA_BIN}" != "" ]]
    then
      if [[ -e ${PZC_NINJA_BIN} ]]
      then
        _pzc_debug "PZC_NINJA_BIN = ${PZC_NINJA_BIN} (user defined)"
      else
        _pzc_warning "Your Ninja is not found. Search other Ninja."
        PZC_NINJA_BIN=""
      fi
    fi
    if [[ "${PZC_NINJA_BIN}" == "" ]]
    then
      if [[ ${_PZC_MISE_AVAILABLE} = 1 ]]
      then
        PZC_NINJA_BIN=$(${PZC_MISE_BIN} which --raw -E ${HOST} -C "${ENVI_DIR}/pzc/progs/mise" ninja 2&>/dev/null)
        if [[ $? == 0 ]]
        then
          _pzc_debug "PZC_NINJA_BIN = ${PZC_NINJA_BIN} (Mise-en-place)"
        fi
      fi
    fi
    if [[ "${PZC_NINJA_BIN}" == "" ]]
    then
      if [[ -x "$(command -v ninja)" ]]
      then
        PZC_NINJA_BIN="ninja"
        _pzc_debug "PZC_NINJA_BIN = ${PZC_NINJA_BIN} (Path)"
      fi
    fi
    if [[ "${PZC_NINJA_BIN}" == "" ]]
    then
      _pzc_warning "Ninja is not installed (https://github.com/ninja-build/ninja). You can install ninja with Mise-en-place with the command 'pzc_install_ninja' or disable ninja search in pzcrc."
    fi
  fi

  echo "PZC_NINJA_BIN=\"${PZC_NINJA_BIN}\"" >> ${PZC_PZC_PKG_LOCATION_FILE}



  # ---------------------------------------
  # CMake
  # ---------------------------------------

  local PZC_ENABLE_CMAKE=$(jq -r '.pzc_config_pkgs.pkgs.cmake.enable' ${PZC_PZC_CONFIG_PKGS})

  if [[ ${PZC_ENABLE_CMAKE} = true ]]
  then
    local PZC_CMAKE_BIN=$(jq -r '.pzc_config_pkgs.pkgs.cmake.executable_path' ${PZC_PZC_CONFIG_PKGS})
    if [[ "${PZC_CMAKE_BIN}" != "" ]]
    then
      if [[ -e ${PZC_CMAKE_BIN} ]]
      then
        _pzc_debug "PZC_CMAKE_BIN = ${PZC_CMAKE_BIN} (user defined)"
      else
        _pzc_warning "Your CMake is not found. Search other CMake."
        PZC_CMAKE_BIN=""
      fi
    fi
    if [[ "${PZC_CMAKE_BIN}" == "" ]]
    then
      if [[ ${_PZC_MISE_AVAILABLE} = 1 ]]
      then
        PZC_CMAKE_BIN=$(${PZC_MISE_BIN} which --raw -E ${HOST} -C "${ENVI_DIR}/pzc/progs/mise" cmake 2&>/dev/null)
        if [[ $? == 0 ]]
        then
          _pzc_debug "PZC_CMAKE_BIN = ${PZC_CMAKE_BIN} (Mise-en-place)"
        fi
      fi
    fi
    if [[ "${PZC_CMAKE_BIN}" == "" ]]
    then
      if [[ -x "$(command -v cmake)" ]]
      then
        PZC_CMAKE_BIN="cmake"
        _pzc_debug "PZC_CMAKE_BIN = ${PZC_CMAKE_BIN} (Path)"
      fi
    fi
    if [[ "${PZC_CMAKE_BIN}" == "" ]]
    then
      _pzc_warning "CMake is not installed (https://github.com/Kitware/CMake). You can install cmake with Mise-en-place with the command 'pzc_install_cmake' or disable cmake search in pzcrc."
    fi
  fi

  echo "PZC_CMAKE_BIN=\"${PZC_CMAKE_BIN}\"" >> ${PZC_PZC_PKG_LOCATION_FILE}



  # ---------------------------------------
  # Taskwarrior
  # ---------------------------------------

  local PZC_ENABLE_TASK=$(jq -r '.pzc_config_pkgs.pkgs.taskwarrior.enable' ${PZC_PZC_CONFIG_PKGS})

  if [[ ${PZC_ENABLE_TASK} = true ]]
  then
    local PZC_TASK_BIN=$(jq -r '.pzc_config_pkgs.pkgs.taskwarrior.executable_path' ${PZC_PZC_CONFIG_PKGS})
    if [[ "${PZC_TASK_BIN}" != "" ]]
    then
      if [[ -e ${PZC_TASK_BIN} ]]
      then
        _pzc_debug "PZC_TASK_BIN = ${PZC_TASK_BIN} (user defined)"
      else
        _pzc_warning "Your Taskwarrior is not found. Search other Taskwarrior."
        PZC_TASK_BIN=""
      fi
    fi
    if [[ "${PZC_TASK_BIN}" == "" ]]
    then
      if [[ -x "$(command -v task)" ]]
      then
        PZC_TASK_BIN="task"
        _pzc_debug "PZC_TASK_BIN = ${PZC_TASK_BIN} (Path)"
      fi
    fi
    if [[ "${PZC_TASK_BIN}" == "" ]]
    then
      _pzc_warning "Taskwarrior is not installed (https://github.com/GothenburgBitFactory/taskwarrior). You can disable taskwarrior search in pzcrc."
    fi
  fi

  echo "PZC_TASK_BIN=\"${PZC_TASK_BIN}\"" >> ${PZC_PZC_PKG_LOCATION_FILE}



  # ---------------------------------------
  # Atuin
  # ---------------------------------------

  local PZC_ENABLE_ATUIN=$(jq -r '.pzc_config_pkgs.pkgs.atuin.enable' ${PZC_PZC_CONFIG_PKGS})
  local PZC_ALIAS_ATUIN=0
  if [[ ${PZC_ENABLE_ATUIN} = true ]]
  then
    local PZC_ATUIN_BIN=$(jq -r '.pzc_config_pkgs.pkgs.atuin.executable_path' ${PZC_PZC_CONFIG_PKGS})
    if [[ "${PZC_ATUIN_BIN}" != "" ]]
    then
      if [[ -e ${PZC_ATUIN_BIN} ]]
      then
        _pzc_debug "PZC_ATUIN_BIN = ${PZC_ATUIN_BIN} (user defined)"
        PZC_ALIAS_ATUIN=1
      else
        _pzc_warning "Your Atuin is not found. Search other Atuin."
        PZC_ATUIN_BIN=""
      fi
    fi
    if [[ "${PZC_ATUIN_BIN}" == "" ]]
    then
      if [[ ${_PZC_MISE_AVAILABLE} = 1 ]]
      then
        PZC_ATUIN_BIN=$(${PZC_MISE_BIN} which --raw -E ${HOST} -C "${ENVI_DIR}/pzc/progs/mise" atuin 2&>/dev/null)
        if [[ $? == 0 ]]
        then
          _pzc_debug "PZC_ATUIN_BIN = ${PZC_ATUIN_BIN} (Mise-en-place)"
          PZC_ALIAS_ATUIN=1
        fi
      fi
    fi
    if [[ "${PZC_ATUIN_BIN}" == "" ]]
    then
      if [[ -x "$(command -v atuin)" ]]
      then
        PZC_ATUIN_BIN=atuin
        _pzc_debug "PZC_ATUIN_BIN = ${PZC_ATUIN_BIN} (Path)"
      fi
    fi
    if [[ "${PZC_ATUIN_BIN}" == "" ]]
    then
      _pzc_warning "Atuin is not installed (https://github.com/atuinsh/atuin). You can install atuin with Mise-en-place with the command 'pzc_install_atuin' or disable atuin search in pzcrc."
    fi

    local PZC_ATUIN_CONFIG_DIR=$(jq -r '.pzc_config_pkgs.pkgs.atuin.config_dir' ${PZC_PZC_CONFIG_PKGS})
    if [[ "${PZC_ATUIN_CONFIG_DIR}" != "" ]]
    then
      if [[ -d ${PZC_ATUIN_CONFIG_DIR} ]]
      then
        _pzc_debug "PZC_ATUIN_CONFIG_DIR = ${PZC_ATUIN_CONFIG_DIR} (user defined)"
      else
        _pzc_warning "Your Atuin config dir is not found. Search default Atuin config dir."
        PZC_ATUIN_CONFIG_DIR=""
      fi
    fi
    if [[ "${PZC_ATUIN_CONFIG_DIR}" == "" ]]
    then
      PZC_ATUIN_CONFIG_DIR=${PZC_PZC_DIR}/progs/atuin/config
      _pzc_debug "PZC_ATUIN_CONFIG_DIR = ${PZC_ATUIN_CONFIG_DIR} (default)"
    fi
  fi

  echo "PZC_ATUIN_BIN=\"${PZC_ATUIN_BIN}\"" >> ${PZC_PZC_PKG_LOCATION_FILE}
  echo "export ATUIN_CONFIG_DIR=\"${PZC_ATUIN_CONFIG_DIR}\"" >> ${PZC_PZC_PKG_LOCATION_FILE}
        
  if [[ ${PZC_ALIAS_ATUIN} = 1 ]]
  then
    echo "alias atuin='${PZC_ATUIN_BIN}'" >> ${PZC_PZC_PKG_LOCATION_FILE}
  fi



  # ---------------------------------------
  # Fzf
  # ---------------------------------------

  local PZC_ENABLE_FZF=$(jq -r '.pzc_config_pkgs.pkgs.fzf.enable' ${PZC_PZC_CONFIG_PKGS})
  local PZC_ALIAS_FZF=0
  if [[ ${PZC_ENABLE_FZF} = true ]]
  then
    local PZC_FZF_BIN=$(jq -r '.pzc_config_pkgs.pkgs.fzf.executable_path' ${PZC_PZC_CONFIG_PKGS})
    if [[ "${PZC_FZF_BIN}" != "" ]]
    then
      if [[ -e ${PZC_FZF_BIN} ]]
      then
        _pzc_debug "PZC_FZF_BIN = ${PZC_FZF_BIN} (user defined)"
        PZC_ALIAS_FZF=1
      else
        _pzc_warning "Your Fzf is not found. Search other Fzf."
        PZC_FZF_BIN=""
      fi
    fi
    if [[ "${PZC_FZF_BIN}" == "" ]]
    then
      if [[ ${_PZC_MISE_AVAILABLE} = 1 ]]
      then
        PZC_FZF_BIN=$(${PZC_MISE_BIN} which --raw -E ${HOST} -C "${ENVI_DIR}/pzc/progs/mise" fzf 2&>/dev/null)
        if [[ $? == 0 ]]
        then
          _pzc_debug "PZC_FZF_BIN = ${PZC_FZF_BIN} (Mise-en-place)"
          PZC_ALIAS_FZF=1
        fi
      fi
    fi
    if [[ "${PZC_FZF_BIN}" == "" ]]
    then
      if [[ -x "$(command -v fzf)" ]]
      then
        PZC_FZF_BIN=fzf
        _pzc_debug "PZC_FZF_BIN = ${PZC_FZF_BIN} (Path)"
      fi
    fi
    if [[ "${PZC_FZF_BIN}" == "" ]]
    then
      _pzc_warning "Fzf is not installed (https://github.com/junegunn/fzf). You can install fzf with Mise-en-place with the command 'pzc_install_fzf' or disable fzf search in pzcrc."
    fi
  fi

  echo "PZC_FZF_BIN=\"${PZC_FZF_BIN}\"" >> ${PZC_PZC_PKG_LOCATION_FILE}
  if [[ ${PZC_ALIAS_EZA} = 1 ]]
  then
    echo "alias fzf='${PZC_FZF_BIN}'" >> ${PZC_PZC_PKG_LOCATION_FILE}
  fi



  # ---------------------------------------
  # Yazi
  # ---------------------------------------

  local PZC_ENABLE_YAZI=$(jq -r '.pzc_config_pkgs.pkgs.yazi.enable' ${PZC_PZC_CONFIG_PKGS})
  local PZC_ALIAS_YAZI=0
  if [[ ${PZC_ENABLE_YAZI} = true ]]
  then
    local PZC_YAZI_BIN=$(jq -r '.pzc_config_pkgs.pkgs.yazi.executable_path' ${PZC_PZC_CONFIG_PKGS})
    if [[ "${PZC_YAZI_BIN}" != "" ]]
    then
      if [[ -e ${PZC_YAZI_BIN} ]]
      then
        _pzc_debug "PZC_YAZI_BIN = ${PZC_YAZI_BIN} (user defined)"
        PZC_ALIAS_YAZI=1
      else
        _pzc_warning "Your Yazi is not found. Search other Yazi."
        PZC_YAZI_BIN=""
      fi
    fi
    if [[ "${PZC_YAZI_BIN}" == "" ]]
    then
      if [[ ${_PZC_MISE_AVAILABLE} = 1 ]]
      then
        PZC_YAZI_BIN=$(${PZC_MISE_BIN} which --raw -E ${HOST} -C "${ENVI_DIR}/pzc/progs/mise" yazi 2&>/dev/null)
        if [[ $? == 0 ]]
        then
          _pzc_debug "PZC_YAZI_BIN = ${PZC_YAZI_BIN} (Mise-en-place)"
          PZC_ALIAS_YAZI=1
        fi
      fi
    fi
    if [[ "${PZC_YAZI_BIN}" == "" ]]
    then
      if [[ -x "$(command -v yazi)" ]]
      then
        PZC_YAZI_BIN=yazi
        _pzc_debug "PZC_YAZI_BIN = ${PZC_YAZI_BIN} (Path)"
      fi
    fi
    if [[ "${PZC_YAZI_BIN}" == "" ]]
    then
      _pzc_warning "Yazi is not installed (https://github.com/sxyazi/yazi). You can install yazi with Mise-en-place with the command 'pzc_install_yazi' or disable yazi search in pzcrc."
    fi
  fi

  echo "PZC_YAZI_BIN=\"${PZC_YAZI_BIN}\"" >> ${PZC_PZC_PKG_LOCATION_FILE}
  if [[ ${PZC_ALIAS_EZA} = 1 ]]
  then
    echo "alias yazi='${PZC_YAZI_BIN}'" >> ${PZC_PZC_PKG_LOCATION_FILE}
  fi



  # ---------------------------------------
  # Python
  # ---------------------------------------

  local PZC_ENABLE_PYTHON=$(jq -r '.pzc_config_pkgs.pkgs.python.enable' ${PZC_PZC_CONFIG_PKGS})
  if [[ ${PZC_ENABLE_PYTHON} = true ]]
  then
    local PZC_PYTHON_BIN=$(jq -r '.pzc_config_pkgs.pkgs.python.executable_path' ${PZC_PZC_CONFIG_PKGS})
    if [[ "${PZC_PYTHON_BIN}" != "" ]]
    then
      if [[ -e ${PZC_PYTHON_BIN} ]]
      then
        _pzc_debug "PZC_PYTHON_BIN = ${PZC_PYTHON_BIN} (user defined)"
      else
        _pzc_warning "Your Python is not found. Search other Python."
        PZC_PYTHON_BIN=""
      fi
    fi
    if [[ "${PZC_PYTHON_BIN}" == "" ]]
    then
      if [[ ${_PZC_MISE_AVAILABLE} = 1 ]]
      then
        PZC_PYTHON_BIN=$(${PZC_MISE_BIN} which --raw -E ${HOST} -C "${ENVI_DIR}/pzc/progs/mise" python 2&>/dev/null)
        if [[ $? == 0 ]]
        then
          _pzc_debug "PZC_PYTHON_BIN = ${PZC_PYTHON_BIN} (Mise-en-place)"
        fi
      fi
    fi
    if [[ "${PZC_PYTHON_BIN}" == "" ]]
    then
      if [[ -x "$(command -v python)" ]]
      then
        PZC_PYTHON_BIN=python
        _pzc_debug "PZC_PYTHON_BIN = ${PZC_PYTHON_BIN} (Path)"
      elif [[ -x "$(command -v python3)" ]]
      then
        PZC_PYTHON_BIN=python3
        _pzc_debug "PZC_PYTHON_BIN = ${PZC_PYTHON_BIN} (Path)"
      fi
    fi
    if [[ "${PZC_PYTHON_BIN}" == "" ]]
    then
      _pzc_warning "Python is not installed. You can install python with Mise-en-place with the command 'pzc_install_python' or disable python search in pzcrc."
    fi
  fi

  echo "PZC_PYTHON_BIN=\"${PZC_PYTHON_BIN}\"" >> ${PZC_PZC_PKG_LOCATION_FILE}



  # ---------------------------------------
  # Mise-en-place
  # ---------------------------------------

  local PZC_ENABLE_MISE=$(jq -r '.pzc_config_pkgs.pkgs.mise_en_place.enable' ${PZC_PZC_CONFIG_PKGS})
  local PZC_ALIAS_MISE=0
  if [[ ${PZC_ENABLE_MISE} = true ]]
  then
    local PZC_MISE_BIN=$(jq -r '.pzc_config_pkgs.pkgs.mise_en_place.executable_path' ${PZC_PZC_CONFIG_PKGS})
    if [[ "${PZC_MISE_BIN}" != "" ]]
    then
      if [[ -e ${PZC_MISE_BIN} ]]
      then
        _pzc_debug "PZC_MISE_BIN = ${PZC_MISE_BIN} (user defined)"
        PZC_ALIAS_MISE=1
      else
        _pzc_warning "Your Mise-en-place is not found. Search other Mise-en-place."
        PZC_MISE_BIN=""
      fi
    fi
    if [[ "${PZC_MISE_BIN}" == "" ]]
    then
      if [[ -x "$(command -v mise)" ]]
      then
        PZC_MISE_BIN=mise
        _pzc_debug "PZC_MISE_BIN = ${PZC_MISE_BIN} (Path)"
      elif [[ -e ${ENVI_DIR}/pzc/progs/mise/mise ]]
      then
        PZC_MISE_BIN=${ENVI_DIR}/pzc/progs/mise/mise
        _pzc_debug "PZC_MISE_BIN = ${PZC_MISE_BIN} (in pzc)"
        PZC_ALIAS_MISE=1
      fi
    fi
    if [[ "${PZC_MISE_BIN}" == "" ]]
    then
      _pzc_warning "Mise-en-place is not installed (https://github.com/jdx/mise). You can install mise-en-place in the PZC environment folder with the command 'pzc_install_mise' or disable mise search in pzcrc."
    fi
  fi

  echo "PZC_MISE_BIN=\"${PZC_MISE_BIN}\"" >> ${PZC_PZC_PKG_LOCATION_FILE}
  if [[ ${PZC_ALIAS_MISE} = 1 ]]
  then
    echo "alias mise='${PZC_MISE_BIN}'" >> ${PZC_PZC_PKG_LOCATION_FILE}
  fi
}
